version: '3'

volumes:
    db:
    redis_data:

services:
  db:
      image: postgres:12
      env_file:
        - ./postgres.env
      networks:
        - codenation-bup-network
      restart: always
      volumes:
        - db:/var/lib/postgresql/data/pgdata
      ports:
        - '5434:5432'
  service-2:
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - db
    networks:
      - codenation-bup-network
    env_file:
      - ./.env
      - ./postgres.env
    entrypoint: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - '8000:8000'
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - codenation-bup-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always
  grafana:
    image: grafana/grafana:8.5.2
    networks:
      - codenation-bup-network
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/datasources/dashboard.yaml
    depends_on:
      # - tempo
      - loki
      - prometheus
      - jaeger

  # tempo:
  #   image: grafana/tempo:1.2.1
  #   ports:
  #     - "14268:14268"
  #   command:
  #     - -config.file=/etc/tempo/tempo.yaml
  #   volumes:
  #     - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.32
    networks:
      - codenation-bup-network
    ports:
      - 16686:16686
      - 6831:6831

  loki:
    image: grafana/loki:2.5.0
    networks:
      - codenation-bup-network
    ports:
      - "3100:3100"
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail:2.5.0
    networks:
      - codenation-bup-network
    volumes:
      - ./promtail/promtail.yaml:/etc/promtail/promtail.yaml
      - ./service-2.log:/var/log/service-2.log
    command: --config.file=/etc/promtail/promtail.yaml
    depends_on:
      - service-2

  prometheus:
    image: prom/prometheus:v2.35.0
    networks:
      - codenation-bup-network
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml

networks:
  codenation-bup-network: