FROM python:3.10
WORKDIR '/app'

COPY ./requirements.txt /app/requirements.txt

RUN apt-get -y update
RUN apt-get -y remove libpq5
RUN apt-get -y install libpq-dev python3-dev
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

COPY . /app/