version: '3'

volumes:
    db:
    redis_data:

services:
  db:
      image: postgres:12
      env_file:
        - ./postgres.env
      networks:
        - codenation-bup-network
      restart: always
      volumes:
        - db:/var/lib/postgresql/data/pgdata
      ports:
        - '5434:5432'
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - db
    networks:
      - codenation-bup-network
    env_file:
      - ./.env
      - ./postgres.env
    entrypoint: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - '8000:8000'
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - codenation-bup-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

networks:
  codenation-bup-network: