global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: webapp-scraper
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'service-2:8000'
        labels:
          app: service-2

  - job_name: redis-scraper
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'redis:6379'
        labels:
          app: redis
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # - job_name: webapi-scraper
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets:
  #         - 'webapi:8001'
  #       labels:
  #         app: webapi